name: Build Test

on: [push]

## Does the same stuff as release
## EXCEPT publishing the artifacts

jobs:
  buildtest:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Remove superfluous metafiles we do not want to pack
        run: |
          rm -r Assets/Editor*

      - name: Pack
        run: npm pack
      - name: Verify
        run: |
          ls com.kagekirin.unitycsharpier*.tgz
          tar tvf com.kagekirin.unitycsharpier*.tgz

      - name: Store package name in env
        run: echo "package_name=`ls com.kagekirin.unitycsharpier*.tgz`" >> $GITHUB_ENV
      - name: Verify package_name in env
        run: echo "${{ env.package_name }}"
